#!/bin/bash

rm -fr *.html




./webmake index pub grants pr 
./webmake teaching tinnovation mentoring
./webmake service work ai health method         
    
mv *.html ../
rm -fr *~


chmod 644 ../*html ../*css

../upload
