#!/bin/bash

rm -fr *.html




./webmake index pub grants 
./webmake pr ai health method         
./webmake teaching tinnovation mentoring tdevelopment
./webmake service work


mv *.html ../
rm -fr *~


chmod 644 ../*html ../*css

cd ..
./upload
cd source
